development:
  adapter: mysql2
  host: localhost
  username: root
  password: ka459942
  database: sakura_market_development
  encoding: utf8

test:
  adapter: mysql2
  host: localhost
  username: root
  password: ka459942
  encoding: utf8
  database: sakura_market_test

production:
  adapter: mysql2
  encoding: unicode
  database: sakura_market_production
  pool: 5